name_or_path: /root/autodl-tmp/mnt/memit/model/gpt2-large
tokenizer_name_or_path: /root/autodl-tmp/mnt/memit/model/gpt2-large
archive: null
block_name: GPT2Block

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16
id: gpt2