name_or_path: /root/autodl-tmp/mnt/memit/model/pythia-2.8b
tokenizer_name_or_path: /root/autodl-tmp/mnt/memit/model/pythia-2.8b
archive: null
block_name: GPTNeoXLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16
id: pythia